### ISSUE TITLE
pth model file

### ISSUE THREAD

**Issue by grdiv** [laugh12321/ApolloScape4mmseg#1]
作者你好，我在b站上看到了您用mmsegmentation在apolloscape上的分割模型，找到了这个仓库，但是我并没有找到mmsegmentation推理时model = init_segmentor(config_file, checkpoint_file, device='cuda:0')需要的checkpoint_file文件，请问能提供我跑一下吗？十分感谢！

**Comment by laugh12321** [comment]
不好意思，这个模型是我们公司内部自用的😂，如果是我自己的项目模型我会开源的
